CREATE DATABASE CSDLGiayNam
GO

USE CSDLGiayNam
GO

CREATE TABLE LOAI_SAN_PHAM
(
ID INT PRIMARY KEY IDENTITY NOT NULL, 
TenLoaiSanPham NVARCHAR(100),
TrangThai BIT, 
ThuTuSapXep DATETIME
)
GO

CREATE TABLE PHAN_QUYEN
(
ID INT PRIMARY KEY IDENTITY NOT NULL, 
TenQuyen NVARCHAR(100),
TrangThai bit
)
GO
CREATE TABLE KHACH_HANG
(
ID INT PRIMARY KEY IDENTITY NOT NULL, 
TenKhachHang NVARCHAR(100), 
Email NVARCHAR(100),
UserName nvarchar(100), 
Pass NVARCHAR(100), 
Address NVARCHAR(100), 
Sdt NVARCHAR(100),
PhanQuyenID INT FOREIGN KEY(PhanQuyenID) REFERENCES dbo.PHAN_QUYEN(ID)
)
GO
CREATE TABLE ORDERS
(
ID INT PRIMARY KEY IDENTITY NOT NULL, 
NgayTao DATETIME, 
TrangThai BIT,
KhachHangID INT FOREIGN KEY(KhachHangID) REFERENCES dbo.KHACH_HANG(ID)
)
GO
CREATE TABLE THUONG_HIEU
(
ID INT PRIMARY KEY IDENTITY NOT NULL,
 TenThuongHieu NVARCHAR(100), 
 ThuTuSapXep INT ,
 TrangThai BIT
 )
 GO
CREATE TABLE LIEN_HE
(ID INT PRIMARY KEY IDENTITY NOT NULL, 
Email NVARCHAR(100), 
NoiDung TEXT, 
NgayTao DATETIME
)
GO
CREATE TABLE GIOI_THIEU
(
ID  INT PRIMARY KEY IDENTITY NOT NULL, 
NoiDung TEXT
)
GO

CREATE TABLE SAN_PHAM
(
ID INT PRIMARY KEY IDENTITY NOT NULL, 
TenSanPham NVARCHAR(100), 
ChiTiet NVARCHAR(100), 
HinhAnh nvarchar(100),
PRICE FLOAT, 
SoLuotXem INT, 
Size int,
NgayTao DATETIME,
SoLuongOrder INT, 
XuatXu NVARCHAR(100), 
TrangThai BIT,
ThuongHieuID INT FOREIGN KEY(ThuongHieuID) REFERENCES dbo.THUONG_HIEU(ID) ,
LoaiSanPhamID INT FOREIGN KEY(LoaiSanPhamID) REFERENCES dbo.LOAI_SAN_PHAM(ID) ,
)
GO
CREATE TABLE ORDER_DETAIL
(
ID INT PRIMARY KEY IDENTITY NOT NULL, 
TongTien FLOAT,
SanPhamID INT FOREIGN KEY(SanPhamID) REFERENCES dbo.SAN_PHAM(ID) ,
OrderID INT FOREIGN KEY(OrderID) REFERENCES dbo.ORDERS(ID) ,
)
GO
